stock_analysis_task:
  description: >
    Collect and summarize recent news articles, press releases, and market analyses related to the stock and its industry.
    Pay special attention to any significant events, market sentiments, and analysts' opinions. Also include upcoming events like earnings and others.
    Make sure to use the most recent data as possible.
    You must *always* return the stock ticker! Use only recent information (Today's Date is {date}).
    Selected company by the customer: {company}
  expected_output: >
    Your final answer MUST be a report that includes a comprehensive summary of the latest news, any notable shifts in market sentiment, and potential impacts on the stock.
    Also make sure to return the stock ticker.
  agent: research_analyst

financial_analysis_task:
  description: >
    Conduct a thorough analysis of the stock's financial health and market performance. This includes examining key financial metrics such as P/E ratio, EPS growth, revenue trends, and debt-to-equity ratio.
    Also, analyze the stock's performance in comparison to its industry peers and overall market trends.
    Make sure to use the most recent data possible.
    You must *always* return the stock ticker! Use only recent information (Today's Date is {date}).
    Selected company by the customer: {company}
  expected_output: >
    Your final report MUST expand on the summary provided but now including a clear assessment of the stock's financial standing, its strengths and weaknesses, and how it fares against its competitors in the current market scenario.
    Always return the stock ticker.
  agent: financial_analyst

filings_analysis_task:
  description: >
    Analyze the latest quarterly and annually income statements for the stock in question. Analyze the stock's fundamentals and focus on key metrics/ratios.
    Focus on key sections like Management's Discussion and Analysis, financial statements, insider trading activity, and any disclosed risks.
    Extract relevant data and insights that could influence the stock's future performance.
    You must *always* return the stock ticker! Use only recent information (Today's Date is {date}).
    Selected company by the customer: {company}
  expected_output: >
    Your final answer must be an expanded report that now also highlights significant findings from these filings, including any red flags or positive indicators for your customer.
    Always return the stock ticker.
  agent: financial_analyst

recommendation_task:
  description: >
    Review and synthesize the analyses provided by the Financial Analyst and the Research Analyst. Combine these insights to form a comprehensive investment recommendation.
    You MUST consider all aspects, including financial health, market sentiment, and qualitative data from annual/quarterly income statements.
    Make sure to include a section that shows insider trading activity, and upcoming events like earnings.
    Your final answer MUST be a recommendation for your customer. It should be a full super detailed report, providing a clear investment stance and strategy with supporting evidence.
    Make it pretty and well formatted for your customer.
    You must *always* return the stock ticker! Use only recent information (Today's Date is {date}).
    Selected company by the customer: {company}
  expected_output: >
    Your final answer MUST be a recommendation for your customer. It should be a full super detailed report, providing a clear investment stance and strategy with supporting evidence.
    Always return the stock ticker.
  agent: investment_advisor

risk_analysis_task:
  description: >
    Conduct a comprehensive risk analysis for the selected stock. This includes evaluating market risks, credit risks, operational risks, and any other potential risks that could impact the stock's performance.
    You must *always* return the stock ticker! Use only recent information (Today's Date is {date}).
    Selected company by the customer: {company}
  expected_output: >
    Your final report MUST include a detailed risk assessment, highlighting any significant risks and their potential impact on the stock's future performance.
    Always return the stock ticker.
  agent: research_analyst
